
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/CLion 2024.2/bin/cmake/win/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.27891 - AMD64
